### ISSUE TITLE
Hi, can I hope to use this tool to bypass the app's thread detection for frida?

### ISSUE THREAD

**Issue by cloud-jie** [lico-n/ZygiskFrida#37] opened 2024-04-30 08:15 UTC
![image](https://github.com/lico-n/ZygiskFrida/assets/63632785/5887aee9-e235-4693-a7cd-6b413e72b0e6)

**Comment by lico-n** [comment] 2024-04-30 15:59
Hey, what application is this?

I am not sure what checks this application runs. ZygiskFrida currently bundles the standard frida gadget. 
You might be able to bypass more checks by using a hardened version of the gadget.

Take https://github.com/hzzheyang/strongR-frida-android for example. You can download the gadget from their release page and try to use their gadget instead of the bundled one. 

https://github.com/lico-n/ZygiskFrida/blob/main/docs/advanced_config.md#injected_libraries

I have been deliberating whether to include an hardened version of a gadget in the ZygiskFrida module by default but for now you can just try it yourself.

**Comment by lico-n** [comment] 2024-05-03 16:45
The patches for the strongR gadget only patches two threads. Apparently frida starts more threads. The patches are also very old by now. You might try your luck in adding your own patches to rename also the other threads. 

Gadget patches are a bit out of scope out of this project though. At least currently, it's more of a delivery mechanism for a gadget and other libs.

**Closed as completed** 2024-05-03 17:27 UTC

**Comment by lico-n** [comment] 2024-05-04 18:02
If this is just the thread names you can try this arm64 gadget

[libgadget.so.zip](https://github.com/lico-n/ZygiskFrida/files/15210531/libgadget.so.zip)

It's completely untested though. Unzip and place in the `re.zyg.fri` directory. Setup permissions or just install the module again without uninstalling. (That should setup permissions in the `re.zyg.fri` directory)

**Comment by lico-n** [comment] 2024-05-05 10:00
Here's a version with `frida-pool` also patched out.

[libgadget.so.zip](https://github.com/lico-n/ZygiskFrida/files/15212399/libgadget.so.zip)

The issue you have is that the frida-server lives within the gadget. It is therefore not possible to spawn processes, you can only attach to it.

For RMS I would recommend you to use `Gadget` as the Package name and choose the `Attach` mode instead of `Spawn`

For objection similarly either omit the `-g` argument or use `-g Gadget` (this is the default)

Don't worry about the coffee, I am just sharing this project so we can all benefit from each other.

**Comment by lico-n** [comment] 2024-05-05 15:27
> Then I used the frida Gadget you mentioned and found that there was no improvement

[libgadget.so.zip](https://github.com/lico-n/ZygiskFrida/files/15213502/libgadget.so.zip)

Try this one, needed a slightly different patch for this. But this one should probably work?

> Finally, this is an invitation. If one day you come to Beijing, the capital of China, please contact me and I will take you to try authentic Chinese food.

Thanks for the invitation. No plans currently but I appreciate it, maybe one day :)

**Comment by lico-n** [comment] 2024-05-06 16:14
The issue is that application is not running on my device/location, so I am unable to give you any specific tips here. 
There are other frida detection methods that are not bypassed by an enhanced gadget/ZygiskFrida like comparing libraries in memory vs disk.

Regarding objection there it is also possible that there is some interference between the gadget remapping process and whatever objection is doing at startup.

I would give these here a try (only includes arm/arm64)

This one delays the remapping by 1 second.
[ZygiskFrida-v1.7.2-zygisk-release.zip](https://github.com/lico-n/ZygiskFrida/files/15223223/ZygiskFrida-v1.7.2-zygisk-release.zip) 

This ones disables the remapping completely (gadget will appear in maps though)
[ZygiskFrida-v1.7.2-zygisk-release.zip](https://github.com/lico-n/ZygiskFrida/files/15223280/ZygiskFrida-v1.7.2-zygisk-release.zip)

Does your script behave the same if you copy paste it in the interactive frida shell instead of passing it as a script?
